eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: ${DISCOVERY-SERVICE-URL}:http://localhost:8761/eureka/
spring:
  cloud:
    discovery:
      enabled: true
    config:
      uri: ${CONFIG_SERVICE_URI}
    gateway:
      routes:
        - id: r1
          uri: lb://SETTINGS-SERVICE
          predicates:
          - Path=/api/v1/address/**
        - id: r2
          uri: lb://LIBRARY-SERVICE
          predicates:
          - Path=/api/v1/library/**
  config:
    import: optional:configserver:${CONFIG_SERVICE_URI}