settings:
  params:
    x: 21
    y: 22

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/settings-service
    username: postgres
    password: donald

  config:
    import: optional:configserver:http://localhost:9899
    cloud:
      config:
        uri: http://localhost:9899

management:
  endpoints:
    web:
      exposure:
        include: '*'
  health:
    refresh:
      enabled: true
server:
  port: 9891