settings:
  params:
    x: 19
    y: 20

spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  config:
    import: optional:configserver:${CONFIG_SERVICE_URI}
  cloud:
    config:
      uri: ${CONFIG_SERVICE_URI}
server:
  port: 9891

management:
  endpoints:
    web:
      exposure:
        include: '*'
  health:
    refresh:
      enabled: true