settings:
  params:
    x: 19
    y: 20

spring:
  datasource:
    #url: ${SPRING_DATASOURCE_URL}
    #username: ${SPRING_DATASOURCE_USERNAME}
    #password: ${SPRING_DATASOURCE_PASSWORD}
    url: jdbc:postgresql://localhost:5432/settings-service
    username: postgres
    password: donald


management:
  endpoints:
    web:
      exposure:
        include: '*'
  health:
    refresh:
      enabled: true