spring:
  application:
    name: CONFIG-SERVER
  cloud:
    config:
      server:
        git:
          uri: https://github.com/amaganadonald/book-configuration.git
          clone-on-start: true
          default-label: main
        native:
          search-locations: https://github.com/amaganadonald/book-configuration.git
          composite:
            - type: git
              uri: https://github.com/amaganadonald/book-configuration.git
              clone-on-start: true
              default-label: main
            - type: native
              search-locations: https://github.com/amaganadonald/book-configuration.git
  discovery:
    enabled: true
server:
  port: 9899

management:
  endpoints:
    web:
      exposure:
        include: "health,refresh,info"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true
eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: ${DISCOVERY-SERVICE-URL}:http://localhost:8761/eureka/